[package]
name = "omnish-store"
version.workspace = true
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = "1"
anyhow = { workspace = true }

[dev-dependencies]
tempfile = "3"
