[package]
name = "omnish-protocol"
version.workspace = true
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = "1"
bincode = { workspace = true }
anyhow = { workspace = true }
omnish-store = { path = "../omnish-store" }
