[package]
name = "omnish-transport"
version = "0.1.0"
edition = "2021"

[dependencies]
omnish-protocol = { path = "../omnish-protocol" }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = "3"
