[package]
name = "omnish-llm"
version.workspace = true
edition = "2021"

[dependencies]
omnish-common = { path = "../omnish-common" }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = "1"
anyhow = { workspace = true }
async-trait = "0.1"
