[package]
name = "omnish-context"
version.workspace = true
edition = "2021"

[dependencies]
omnish-store = { path = "../omnish-store" }
anyhow = { workspace = true }
async-trait = "0.1"

[dev-dependencies]
tokio = { workspace = true }
