[package]
name = "omnish-common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
toml = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
toml = { workspace = true }
