[package]
name = "omnish-common"
version.workspace = true
edition = "2021"

[dependencies]
serde = { workspace = true }
toml = { workspace = true }
anyhow = { workspace = true }
dirs = "5"

[dev-dependencies]
toml = { workspace = true }
